version: '3.8'

services:
  web-demo-backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    # env_file:
    #   - .env
    volumes:
      - .:/app
    command: ["uvicorn", "web_demo_backend.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]